// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// OAuth2Client is the predicate function for oauth2client builders.
type OAuth2Client func(*sql.Selector)

// OAuth2Token is the predicate function for oauth2token builders.
type OAuth2Token func(*sql.Selector)

// Shorts is the predicate function for shorts builders.
type Shorts func(*sql.Selector)
