schema:
  - ../schema/graphql/oauth2_client.graphql
documents:
  # - src/components/**/*.{graphql,js,jsx,ts,tsx}
  - src/graphql/queries/**/*.graphql
  - src/graphql/mutations/**/*.graphql
  # - src/graphql/fragments/**/*.graphql
extensions:
  codegen:
    overwrite: true
    generates:
      src/graphql/generated/index.ts:
        plugins:
          - typescript
          - typescript-operations # query, mutationから型を作成
          - typescript-react-apollo # query, mutationからhooks, hocを作成
        config:
          withHooks: true
    hooks:
      afterOneFileWrite:
        - prettier --write
