receivers:
  otlp:
    protocols:
      grpc:
  jaeger:
    protocols:
      grpc:

exporters:
  logging:

  otlp/jaeger:
    endpoint: otel-jaeger:4317
    tls:
      insecure: true

processors:
  batch:
    timeout: 1s
    send_batch_size: 5

extensions:
  health_check:

service:
  extensions:
    - health_check
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlp/jaeger
        - logging
