components:
  schemas:
    request.GenerateShortURL:
      properties:
        key:
          description: nullable
          type: string
        url:
          type: string
      type: object
    request.RevokeToken:
      properties:
        token:
          type: string
        token_type_hint:
          description: Enums(access_token,refresh_token)
          type: string
      type: object
    response.Error:
      properties:
        description:
          type: string
        field:
          type: string
        help:
          type: string
        message:
          type: string
      type: object
    response.Errors:
      properties:
        errors:
          items:
            $ref: '#/components/schemas/response.Error'
          type: array
          uniqueItems: false
      type: object
    response.GenerateShortURL:
      properties:
        url:
          type: string
      type: object
    response.OAuth2Token:
      properties:
        access_token:
          type: string
        expires_in:
          type: integer
        refresh_token:
          description: nullable
          type: string
        scope:
          description: nullable
          type: string
        token_type:
          type: string
      type: object
    response.Shorts:
      properties:
        author:
          type: string
        created_at:
          type: string
        key:
          type: string
        updated_at:
          type: string
        url:
          type: string
      type: object
  securitySchemes:
    OAuth2Application:
      description: エンドポイントを保護します
      flows:
        clientCredentials:
          tokenUrl: /api/v1/oauth2/token
      in: header
      type: oauth2
externalDocs:
  description: ""
  url: ""
info:
  description: 短縮URL生成 API
  license:
    name: nozomi.nishinohara
  title: Short url
  version: "1.0"
openapi: 3.1.0
paths:
  /oauth2:
    get:
      operationId: OAuthApplicationList
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.Errors'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.Errors'
          description: Unauthorized
      security:
      - OAuth2Application: []
      summary: 登録されているOAuthアプリケーションの一覧
      tags:
      - API
  /oauth2/revoke:
    post:
      operationId: RevokeOAuthToken
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/request.RevokeToken'
        description: revoke token
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.Errors'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.Errors'
          description: Unauthorized
      security:
      - OAuth2Application: []
      summary: アクセストークンの取消
      tags:
      - API
  /oauth2/token:
    post:
      operationId: OAuthTokenRequest
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              enum:
              - client_credentials
              type: string
        description: grant_type
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.OAuth2Token'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.Errors'
          description: Bad Request
      summary: アクセストークンの生成
      tags:
      - API
  /shorts:
    get:
      operationId: ShortURLList
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.Shorts'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.Errors'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.Errors'
          description: Unauthorized
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.Errors'
          description: Internal Server Error
      security:
      - OAuth2Application: []
      summary: 短縮URLの一覧
      tags:
      - API
  /shorts/{key}:
    delete:
      operationId: RemoveShortURL
      parameters:
      - description: short url key
        in: path
        name: key
        required: true
        schema:
          type: string
      responses:
        "204":
          description: No Content
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.Errors'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.Errors'
          description: Unauthorized
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.Errors'
          description: Internal Server Error
      security:
      - OAuth2Application: []
      summary: 短縮URLの削除
      tags:
      - API
  /shorts/{key}/qrcode:
    get:
      operationId: GenerateQRCode
      parameters:
      - description: short url request
        in: path
        name: key
        schema:
          type: string
      responses:
        "200":
          content:
            image/png:
              schema:
                format: binary
                type: string
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.Errors'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.Errors'
          description: Unauthorized
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.Errors'
          description: Internal Server Error
      security:
      - OAuth2Application: []
      summary: 短縮URLのQRコード生成
      tags:
      - API
  /shorts/generate:
    post:
      operationId: GenerateShortURL
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/request.GenerateShortURL'
        description: generate short url request
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.GenerateShortURL'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.Errors'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.Errors'
          description: Unauthorized
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response.Errors'
          description: Internal Server Error
      security:
      - OAuth2Application: []
      summary: 短縮URLの生成
      tags:
      - API
