// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/n-creativesystem/short-url/pkg/infrastructure/rdb/ent/oauth2token"
)

// OAuth2TokenCreate is the builder for creating a OAuth2Token entity.
type OAuth2TokenCreate struct {
	config
	mutation *OAuth2TokenMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (oc *OAuth2TokenCreate) SetCreateTime(t time.Time) *OAuth2TokenCreate {
	oc.mutation.SetCreateTime(t)
	return oc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (oc *OAuth2TokenCreate) SetNillableCreateTime(t *time.Time) *OAuth2TokenCreate {
	if t != nil {
		oc.SetCreateTime(*t)
	}
	return oc
}

// SetUpdateTime sets the "update_time" field.
func (oc *OAuth2TokenCreate) SetUpdateTime(t time.Time) *OAuth2TokenCreate {
	oc.mutation.SetUpdateTime(t)
	return oc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (oc *OAuth2TokenCreate) SetNillableUpdateTime(t *time.Time) *OAuth2TokenCreate {
	if t != nil {
		oc.SetUpdateTime(*t)
	}
	return oc
}

// SetExpiredAt sets the "expired_at" field.
func (oc *OAuth2TokenCreate) SetExpiredAt(i int64) *OAuth2TokenCreate {
	oc.mutation.SetExpiredAt(i)
	return oc
}

// SetCode sets the "code" field.
func (oc *OAuth2TokenCreate) SetCode(s string) *OAuth2TokenCreate {
	oc.mutation.SetCode(s)
	return oc
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (oc *OAuth2TokenCreate) SetNillableCode(s *string) *OAuth2TokenCreate {
	if s != nil {
		oc.SetCode(*s)
	}
	return oc
}

// SetAccess sets the "access" field.
func (oc *OAuth2TokenCreate) SetAccess(s string) *OAuth2TokenCreate {
	oc.mutation.SetAccess(s)
	return oc
}

// SetNillableAccess sets the "access" field if the given value is not nil.
func (oc *OAuth2TokenCreate) SetNillableAccess(s *string) *OAuth2TokenCreate {
	if s != nil {
		oc.SetAccess(*s)
	}
	return oc
}

// SetRefresh sets the "refresh" field.
func (oc *OAuth2TokenCreate) SetRefresh(s string) *OAuth2TokenCreate {
	oc.mutation.SetRefresh(s)
	return oc
}

// SetNillableRefresh sets the "refresh" field if the given value is not nil.
func (oc *OAuth2TokenCreate) SetNillableRefresh(s *string) *OAuth2TokenCreate {
	if s != nil {
		oc.SetRefresh(*s)
	}
	return oc
}

// SetData sets the "data" field.
func (oc *OAuth2TokenCreate) SetData(s string) *OAuth2TokenCreate {
	oc.mutation.SetData(s)
	return oc
}

// SetNillableData sets the "data" field if the given value is not nil.
func (oc *OAuth2TokenCreate) SetNillableData(s *string) *OAuth2TokenCreate {
	if s != nil {
		oc.SetData(*s)
	}
	return oc
}

// SetID sets the "id" field.
func (oc *OAuth2TokenCreate) SetID(i int64) *OAuth2TokenCreate {
	oc.mutation.SetID(i)
	return oc
}

// Mutation returns the OAuth2TokenMutation object of the builder.
func (oc *OAuth2TokenCreate) Mutation() *OAuth2TokenMutation {
	return oc.mutation
}

// Save creates the OAuth2Token in the database.
func (oc *OAuth2TokenCreate) Save(ctx context.Context) (*OAuth2Token, error) {
	oc.defaults()
	return withHooks(ctx, oc.sqlSave, oc.mutation, oc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (oc *OAuth2TokenCreate) SaveX(ctx context.Context) *OAuth2Token {
	v, err := oc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (oc *OAuth2TokenCreate) Exec(ctx context.Context) error {
	_, err := oc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oc *OAuth2TokenCreate) ExecX(ctx context.Context) {
	if err := oc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (oc *OAuth2TokenCreate) defaults() {
	if _, ok := oc.mutation.CreateTime(); !ok {
		v := oauth2token.DefaultCreateTime()
		oc.mutation.SetCreateTime(v)
	}
	if _, ok := oc.mutation.UpdateTime(); !ok {
		v := oauth2token.DefaultUpdateTime()
		oc.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (oc *OAuth2TokenCreate) check() error {
	if _, ok := oc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "OAuth2Token.create_time"`)}
	}
	if _, ok := oc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "OAuth2Token.update_time"`)}
	}
	if _, ok := oc.mutation.ExpiredAt(); !ok {
		return &ValidationError{Name: "expired_at", err: errors.New(`ent: missing required field "OAuth2Token.expired_at"`)}
	}
	if v, ok := oc.mutation.Code(); ok {
		if err := oauth2token.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "OAuth2Token.code": %w`, err)}
		}
	}
	if v, ok := oc.mutation.Access(); ok {
		if err := oauth2token.AccessValidator(v); err != nil {
			return &ValidationError{Name: "access", err: fmt.Errorf(`ent: validator failed for field "OAuth2Token.access": %w`, err)}
		}
	}
	if v, ok := oc.mutation.Refresh(); ok {
		if err := oauth2token.RefreshValidator(v); err != nil {
			return &ValidationError{Name: "refresh", err: fmt.Errorf(`ent: validator failed for field "OAuth2Token.refresh": %w`, err)}
		}
	}
	return nil
}

func (oc *OAuth2TokenCreate) sqlSave(ctx context.Context) (*OAuth2Token, error) {
	if err := oc.check(); err != nil {
		return nil, err
	}
	_node, _spec := oc.createSpec()
	if err := sqlgraph.CreateNode(ctx, oc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	oc.mutation.id = &_node.ID
	oc.mutation.done = true
	return _node, nil
}

func (oc *OAuth2TokenCreate) createSpec() (*OAuth2Token, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuth2Token{config: oc.config}
		_spec = sqlgraph.NewCreateSpec(oauth2token.Table, sqlgraph.NewFieldSpec(oauth2token.FieldID, field.TypeInt64))
	)
	if id, ok := oc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := oc.mutation.CreateTime(); ok {
		_spec.SetField(oauth2token.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := oc.mutation.UpdateTime(); ok {
		_spec.SetField(oauth2token.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := oc.mutation.ExpiredAt(); ok {
		_spec.SetField(oauth2token.FieldExpiredAt, field.TypeInt64, value)
		_node.ExpiredAt = value
	}
	if value, ok := oc.mutation.Code(); ok {
		_spec.SetField(oauth2token.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := oc.mutation.Access(); ok {
		_spec.SetField(oauth2token.FieldAccess, field.TypeString, value)
		_node.Access = value
	}
	if value, ok := oc.mutation.Refresh(); ok {
		_spec.SetField(oauth2token.FieldRefresh, field.TypeString, value)
		_node.Refresh = value
	}
	if value, ok := oc.mutation.Data(); ok {
		_spec.SetField(oauth2token.FieldData, field.TypeString, value)
		_node.Data = value
	}
	return _node, _spec
}

// OAuth2TokenCreateBulk is the builder for creating many OAuth2Token entities in bulk.
type OAuth2TokenCreateBulk struct {
	config
	builders []*OAuth2TokenCreate
}

// Save creates the OAuth2Token entities in the database.
func (ocb *OAuth2TokenCreateBulk) Save(ctx context.Context) ([]*OAuth2Token, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ocb.builders))
	nodes := make([]*OAuth2Token, len(ocb.builders))
	mutators := make([]Mutator, len(ocb.builders))
	for i := range ocb.builders {
		func(i int, root context.Context) {
			builder := ocb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuth2TokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ocb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ocb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ocb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ocb *OAuth2TokenCreateBulk) SaveX(ctx context.Context) []*OAuth2Token {
	v, err := ocb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ocb *OAuth2TokenCreateBulk) Exec(ctx context.Context) error {
	_, err := ocb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ocb *OAuth2TokenCreateBulk) ExecX(ctx context.Context) {
	if err := ocb.Exec(ctx); err != nil {
		panic(err)
	}
}
