// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/n-creativesystem/short-url/pkg/infrastructure/rdb/ent/oauth2client"
	"github.com/n-creativesystem/short-url/pkg/infrastructure/rdb/ent/predicate"
	"github.com/n-creativesystem/short-url/pkg/utils/credentials"
)

// OAuth2ClientUpdate is the builder for updating OAuth2Client entities.
type OAuth2ClientUpdate struct {
	config
	hooks    []Hook
	mutation *OAuth2ClientMutation
}

// Where appends a list predicates to the OAuth2ClientUpdate builder.
func (ou *OAuth2ClientUpdate) Where(ps ...predicate.OAuth2Client) *OAuth2ClientUpdate {
	ou.mutation.Where(ps...)
	return ou
}

// SetUpdateTime sets the "update_time" field.
func (ou *OAuth2ClientUpdate) SetUpdateTime(t time.Time) *OAuth2ClientUpdate {
	ou.mutation.SetUpdateTime(t)
	return ou
}

// SetSecret sets the "secret" field.
func (ou *OAuth2ClientUpdate) SetSecret(cs credentials.EncryptString) *OAuth2ClientUpdate {
	ou.mutation.SetSecret(cs)
	return ou
}

// SetDomain sets the "domain" field.
func (ou *OAuth2ClientUpdate) SetDomain(cs credentials.EncryptString) *OAuth2ClientUpdate {
	ou.mutation.SetDomain(cs)
	return ou
}

// SetPublic sets the "public" field.
func (ou *OAuth2ClientUpdate) SetPublic(b bool) *OAuth2ClientUpdate {
	ou.mutation.SetPublic(b)
	return ou
}

// SetUserID sets the "user_id" field.
func (ou *OAuth2ClientUpdate) SetUserID(s string) *OAuth2ClientUpdate {
	ou.mutation.SetUserID(s)
	return ou
}

// SetAppName sets the "app_name" field.
func (ou *OAuth2ClientUpdate) SetAppName(s string) *OAuth2ClientUpdate {
	ou.mutation.SetAppName(s)
	return ou
}

// Mutation returns the OAuth2ClientMutation object of the builder.
func (ou *OAuth2ClientUpdate) Mutation() *OAuth2ClientMutation {
	return ou.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ou *OAuth2ClientUpdate) Save(ctx context.Context) (int, error) {
	ou.defaults()
	return withHooks(ctx, ou.sqlSave, ou.mutation, ou.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ou *OAuth2ClientUpdate) SaveX(ctx context.Context) int {
	affected, err := ou.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ou *OAuth2ClientUpdate) Exec(ctx context.Context) error {
	_, err := ou.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ou *OAuth2ClientUpdate) ExecX(ctx context.Context) {
	if err := ou.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ou *OAuth2ClientUpdate) defaults() {
	if _, ok := ou.mutation.UpdateTime(); !ok {
		v := oauth2client.UpdateDefaultUpdateTime()
		ou.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ou *OAuth2ClientUpdate) check() error {
	if v, ok := ou.mutation.Secret(); ok {
		if err := oauth2client.SecretValidator(v.String()); err != nil {
			return &ValidationError{Name: "secret", err: fmt.Errorf(`ent: validator failed for field "OAuth2Client.secret": %w`, err)}
		}
	}
	if v, ok := ou.mutation.Domain(); ok {
		if err := oauth2client.DomainValidator(v.String()); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "OAuth2Client.domain": %w`, err)}
		}
	}
	if v, ok := ou.mutation.UserID(); ok {
		if err := oauth2client.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "OAuth2Client.user_id": %w`, err)}
		}
	}
	if v, ok := ou.mutation.AppName(); ok {
		if err := oauth2client.AppNameValidator(v); err != nil {
			return &ValidationError{Name: "app_name", err: fmt.Errorf(`ent: validator failed for field "OAuth2Client.app_name": %w`, err)}
		}
	}
	return nil
}

func (ou *OAuth2ClientUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ou.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauth2client.Table, oauth2client.Columns, sqlgraph.NewFieldSpec(oauth2client.FieldID, field.TypeString))
	if ps := ou.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ou.mutation.UpdateTime(); ok {
		_spec.SetField(oauth2client.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := ou.mutation.Secret(); ok {
		_spec.SetField(oauth2client.FieldSecret, field.TypeString, value)
	}
	if value, ok := ou.mutation.Domain(); ok {
		_spec.SetField(oauth2client.FieldDomain, field.TypeString, value)
	}
	if value, ok := ou.mutation.Public(); ok {
		_spec.SetField(oauth2client.FieldPublic, field.TypeBool, value)
	}
	if value, ok := ou.mutation.UserID(); ok {
		_spec.SetField(oauth2client.FieldUserID, field.TypeString, value)
	}
	if value, ok := ou.mutation.AppName(); ok {
		_spec.SetField(oauth2client.FieldAppName, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ou.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauth2client.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ou.mutation.done = true
	return n, nil
}

// OAuth2ClientUpdateOne is the builder for updating a single OAuth2Client entity.
type OAuth2ClientUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuth2ClientMutation
}

// SetUpdateTime sets the "update_time" field.
func (ouo *OAuth2ClientUpdateOne) SetUpdateTime(t time.Time) *OAuth2ClientUpdateOne {
	ouo.mutation.SetUpdateTime(t)
	return ouo
}

// SetSecret sets the "secret" field.
func (ouo *OAuth2ClientUpdateOne) SetSecret(cs credentials.EncryptString) *OAuth2ClientUpdateOne {
	ouo.mutation.SetSecret(cs)
	return ouo
}

// SetDomain sets the "domain" field.
func (ouo *OAuth2ClientUpdateOne) SetDomain(cs credentials.EncryptString) *OAuth2ClientUpdateOne {
	ouo.mutation.SetDomain(cs)
	return ouo
}

// SetPublic sets the "public" field.
func (ouo *OAuth2ClientUpdateOne) SetPublic(b bool) *OAuth2ClientUpdateOne {
	ouo.mutation.SetPublic(b)
	return ouo
}

// SetUserID sets the "user_id" field.
func (ouo *OAuth2ClientUpdateOne) SetUserID(s string) *OAuth2ClientUpdateOne {
	ouo.mutation.SetUserID(s)
	return ouo
}

// SetAppName sets the "app_name" field.
func (ouo *OAuth2ClientUpdateOne) SetAppName(s string) *OAuth2ClientUpdateOne {
	ouo.mutation.SetAppName(s)
	return ouo
}

// Mutation returns the OAuth2ClientMutation object of the builder.
func (ouo *OAuth2ClientUpdateOne) Mutation() *OAuth2ClientMutation {
	return ouo.mutation
}

// Where appends a list predicates to the OAuth2ClientUpdate builder.
func (ouo *OAuth2ClientUpdateOne) Where(ps ...predicate.OAuth2Client) *OAuth2ClientUpdateOne {
	ouo.mutation.Where(ps...)
	return ouo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ouo *OAuth2ClientUpdateOne) Select(field string, fields ...string) *OAuth2ClientUpdateOne {
	ouo.fields = append([]string{field}, fields...)
	return ouo
}

// Save executes the query and returns the updated OAuth2Client entity.
func (ouo *OAuth2ClientUpdateOne) Save(ctx context.Context) (*OAuth2Client, error) {
	ouo.defaults()
	return withHooks(ctx, ouo.sqlSave, ouo.mutation, ouo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ouo *OAuth2ClientUpdateOne) SaveX(ctx context.Context) *OAuth2Client {
	node, err := ouo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ouo *OAuth2ClientUpdateOne) Exec(ctx context.Context) error {
	_, err := ouo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ouo *OAuth2ClientUpdateOne) ExecX(ctx context.Context) {
	if err := ouo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ouo *OAuth2ClientUpdateOne) defaults() {
	if _, ok := ouo.mutation.UpdateTime(); !ok {
		v := oauth2client.UpdateDefaultUpdateTime()
		ouo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ouo *OAuth2ClientUpdateOne) check() error {
	if v, ok := ouo.mutation.Secret(); ok {
		if err := oauth2client.SecretValidator(v.String()); err != nil {
			return &ValidationError{Name: "secret", err: fmt.Errorf(`ent: validator failed for field "OAuth2Client.secret": %w`, err)}
		}
	}
	if v, ok := ouo.mutation.Domain(); ok {
		if err := oauth2client.DomainValidator(v.String()); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "OAuth2Client.domain": %w`, err)}
		}
	}
	if v, ok := ouo.mutation.UserID(); ok {
		if err := oauth2client.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "OAuth2Client.user_id": %w`, err)}
		}
	}
	if v, ok := ouo.mutation.AppName(); ok {
		if err := oauth2client.AppNameValidator(v); err != nil {
			return &ValidationError{Name: "app_name", err: fmt.Errorf(`ent: validator failed for field "OAuth2Client.app_name": %w`, err)}
		}
	}
	return nil
}

func (ouo *OAuth2ClientUpdateOne) sqlSave(ctx context.Context) (_node *OAuth2Client, err error) {
	if err := ouo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauth2client.Table, oauth2client.Columns, sqlgraph.NewFieldSpec(oauth2client.FieldID, field.TypeString))
	id, ok := ouo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuth2Client.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ouo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauth2client.FieldID)
		for _, f := range fields {
			if !oauth2client.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauth2client.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ouo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ouo.mutation.UpdateTime(); ok {
		_spec.SetField(oauth2client.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := ouo.mutation.Secret(); ok {
		_spec.SetField(oauth2client.FieldSecret, field.TypeString, value)
	}
	if value, ok := ouo.mutation.Domain(); ok {
		_spec.SetField(oauth2client.FieldDomain, field.TypeString, value)
	}
	if value, ok := ouo.mutation.Public(); ok {
		_spec.SetField(oauth2client.FieldPublic, field.TypeBool, value)
	}
	if value, ok := ouo.mutation.UserID(); ok {
		_spec.SetField(oauth2client.FieldUserID, field.TypeString, value)
	}
	if value, ok := ouo.mutation.AppName(); ok {
		_spec.SetField(oauth2client.FieldAppName, field.TypeString, value)
	}
	_node = &OAuth2Client{config: ouo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ouo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauth2client.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ouo.mutation.done = true
	return _node, nil
}
