-- +goose Up
-- create "oauth2_token" table
CREATE TABLE "oauth2_token" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "expired_at" bigint NOT NULL, "code" character varying NULL DEFAULT '', "access" character varying NULL DEFAULT '', "refresh" character varying NULL DEFAULT '', "data" text NULL, PRIMARY KEY ("id"));
-- create index "idx_access" to table: "oauth2_token"
CREATE UNIQUE INDEX "idx_access" ON "oauth2_token" ("access");
-- create index "idx_code" to table: "oauth2_token"
CREATE UNIQUE INDEX "idx_code" ON "oauth2_token" ("code");
-- create index "idx_expired_at" to table: "oauth2_token"
CREATE UNIQUE INDEX "idx_expired_at" ON "oauth2_token" ("expired_at");
-- create index "idx_refresh" to table: "oauth2_token"
CREATE UNIQUE INDEX "idx_refresh" ON "oauth2_token" ("refresh");

-- +goose Down
-- reverse: create index "idx_refresh" to table: "oauth2_token"
DROP INDEX "idx_refresh";
-- reverse: create index "idx_expired_at" to table: "oauth2_token"
DROP INDEX "idx_expired_at";
-- reverse: create index "idx_code" to table: "oauth2_token"
DROP INDEX "idx_code";
-- reverse: create index "idx_access" to table: "oauth2_token"
DROP INDEX "idx_access";
-- reverse: create "oauth2_token" table
DROP TABLE "oauth2_token";
