-- +goose Up
-- create "shorts" table
CREATE TABLE "shorts" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "key" character varying NOT NULL, "url" character varying NOT NULL, "author" character varying NOT NULL, PRIMARY KEY ("id"));

-- +goose Down
-- reverse: create "shorts" table
DROP TABLE "shorts";
