name: Validate renovate config

on:
  push:
    branches:
      - main
    paths:
      - 'renovate.json'
  pull_request:
    paths:
      - 'renovate.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rinchsan/renovate-config-validator@v0.0.12
        with:
          pattern: 'renovate.json'
